export const mockProperties = [
  {
    id: 1,
    title: "فيلا عصرية في تلال أبها",
    type: "sale" as const,
    category: "فيلا",
    bedrooms: 4,
    bathrooms: 3,
    area: 350,
    location: "تلال أبها",
    publishDate: "2024-01-15",
    image: "/placeholder.svg?height=300&width=400",
    description: "فيلا عصرية جميلة مع إطلالات جبلية خلابة، غرف واسعة ولمسات نهائية راقية.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 2,
    title: "شقة فاخرة وسط المدينة",
    type: "rent" as const,
    category: "شقة",
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    location: "وسط أبها",
    publishDate: "2024-01-10",
    image: "/placeholder.svg?height=300&width=400",
    description: "شقة فاخرة في قلب وسط المدينة مع وسائل الراحة الحديثة وإطلالات على المدينة.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 3,
    title: "منزل عائلي مع حديقة",
    type: "sale" as const,
    category: "منزل",
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    location: "المفتاحة",
    publishDate: "2024-01-08",
    image: "/placeholder.svg?height=300&width=400",
    description: "منزل عائلي واسع مع حديقة جميلة وهندسة معمارية تقليدية.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 4,
    title: "مساحة مكتبية تجارية",
    type: "rent" as const,
    category: "مكتب",
    bedrooms: 0,
    bathrooms: 2,
    area: 150,
    location: "الحي التجاري",
    publishDate: "2024-01-05",
    image: "/placeholder.svg?height=300&width=400",
    description: "مساحة مكتبية حديثة مثالية للشركات، مع موقف سيارات وموقع ممتاز.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 5,
    title: "بنتهاوس مع تراس",
    type: "sale" as const,
    category: "شقة",
    bedrooms: 3,
    bathrooms: 3,
    area: 250,
    location: "مركز أبها",
    publishDate: "2024-01-03",
    image: "/placeholder.svg?height=300&width=400",
    description: "بنتهاوس مذهل مع تراس كبير وإطلالات بانورامية على المدينة.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 6,
    title: "منزل تقليدي مطلوب",
    type: "wanted" as const,
    category: "منزل",
    bedrooms: 4,
    bathrooms: 2,
    area: 300,
    location: "أبها القديمة",
    publishDate: "2024-01-01",
    image: "/placeholder.svg?height=300&width=400",
    description: "نبحث عن منزل تقليدي بهندسة معمارية أصيلة في منطقة أبها القديمة.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 7,
    title: "شقة استوديو",
    type: "rent" as const,
    category: "شقة",
    bedrooms: 1,
    bathrooms: 1,
    area: 60,
    location: "المنطقة الجامعية",
    publishDate: "2023-12-28",
    image: "/placeholder.svg?height=300&width=400",
    description: "شقة استوديو مريحة مثالية للطلاب أو المهنيين الشباب.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 8,
    title: "فيلا بإطلالة جبلية",
    type: "sale" as const,
    category: "فيلا",
    bedrooms: 5,
    bathrooms: 4,
    area: 450,
    location: "مرتفعات عسير",
    publishDate: "2023-12-25",
    image: "/placeholder.svg?height=300&width=400",
    description: "فيلا فاخرة مع إطلالات جبلية خلابة ووسائل راحة راقية.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 9,
    title: "مساحة تجارية للإيجار",
    type: "rent" as const,
    category: "مكتب",
    bedrooms: 0,
    bathrooms: 1,
    area: 80,
    location: "منطقة التسوق",
    publishDate: "2023-12-22",
    image: "/placeholder.svg?height=300&width=400",
    description: "مساحة تجارية ممتازة في منطقة تسوق مزدحمة مع حركة مرور عالية.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 10,
    title: "شقة دوبلكس",
    type: "sale" as const,
    category: "شقة",
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    location: "أبها الجديدة",
    publishDate: "2023-12-20",
    image: "/placeholder.svg?height=300&width=400",
    description: "شقة دوبلكس واسعة بتصميم عصري وموقع ممتاز.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 11,
    title: "مساحة مستودع",
    type: "rent" as const,
    category: "مكتب",
    bedrooms: 0,
    bathrooms: 2,
    area: 500,
    location: "المنطقة الصناعية",
    publishDate: "2023-12-18",
    image: "/placeholder.svg?height=300&width=400",
    description: "مساحة مستودع كبيرة مناسبة للتخزين والتوزيع.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 12,
    title: "منزل عائلي مريح",
    type: "wanted" as const,
    category: "منزل",
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    location: "المنطقة السكنية",
    publishDate: "2023-12-15",
    image: "/placeholder.svg?height=300&width=400",
    description: "نبحث عن منزل عائلي مريح في حي سكني هادئ.",
    mapLink: "https://maps.google.com",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
]

export const mockNews = [
  {
    id: 1,
    title: "اتجاهات السوق العقاري في أبها 2024",
    excerpt: "تحليل اتجاهات السوق العقاري الحالية والتوقعات للعام القادم في منطقة أبها.",
    content:
      "أظهر السوق العقاري في أبها نمواً ملحوظاً في عام 2024، حيث ارتفعت قيم العقارات بنسبة 15% مقارنة بالعام السابق. يُعزى هذا النمو إلى عدة عوامل منها تطوير البنية التحتية، ونمو السياحة، والمبادرات الحكومية لتعزيز المنطقة. ازداد الطلب بشكل خاص على الفلل الفاخرة والشقق العصرية، حيث أظهر العديد من المستثمرين اهتماماً بالمنطقة. يتوقع خبراء السوق استمرار النمو طوال العام، مما يجعله وقتاً ممتازاً للمشترين والبائعين للدخول في السوق.",
    publishDate: "2024-01-20",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 2,
    title: "مشاريع البنية التحتية الجديدة تعزز قيم العقارات",
    excerpt: "التطورات الحديثة في البنية التحتية تؤثر بشكل كبير على قيم العقارات في جميع أنحاء المنطقة.",
    content:
      "أدى إنجاز مشاريع البنية التحتية الرئيسية بما في ذلك الطرق الجديدة ومراكز التسوق والمرافق الترفيهية إلى زيادة كبيرة في قيم العقارات في جميع أنحاء أبها. الطريق السريع الجديد الذي يربط أبها بالمدن الرئيسية قلل من وقت السفر وزاد من إمكانية الوصول، مما جعل المنطقة أكثر جاذبية للمقيمين والمستثمرين المحتملين. شهدت قيم العقارات في المناطق القريبة من هذه التطورات الجديدة زيادات تصل إلى 20%، ويتوقع الخبراء نمواً إضافياً مع إنجاز المزيد من المشاريع.",
    publishDate: "2024-01-18",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 3,
    title: "ممارسات البناء المستدام تكتسب شعبية",
    excerpt: "تقنيات البناء الأخضر والممارسات المستدامة تصبح شائعة بشكل متزايد بين المطورين.",
    content:
      "يتبنى المطورون في أبها بشكل متزايد ممارسات البناء المستدام والتقنيات الخضراء في مشاريعهم الجديدة. الألواح الشمسية والأنظمة الموفرة للطاقة والمواد الصديقة للبيئة تصبح ميزات قياسية في التطورات الجديدة. هذا التحول نحو الاستدامة ليس مفيداً للبيئة فحسب، بل جذاب أيضاً للمشترين الذين يبحثون عن منازل موفرة للطاقة تقلل من التكاليف طويلة المدى. العقارات التي تحمل شهادات خضراء تحقق أسعاراً مميزة في السوق.",
    publishDate: "2024-01-15",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 4,
    title: "نمو السياحة يدفع الطلب على سوق الإيجار",
    excerpt: "صناعة السياحة المتنامية تخلق فرصاً جديدة في سوق الإيجار قصير المدى.",
    content:
      "سمعة أبها المتنامية كوجهة سياحية تخلق فرصاً كبيرة في سوق الإيجار، خاصة للإيجارات قصيرة المدى. أصحاب العقارات يحولون عقاراتهم بشكل متزايد إلى إيجارات سياحية للاستفادة من تدفق السياح. هذا الاتجاه أدى إلى عوائد إيجار أعلى وزيادة الطلب على العقارات في المواقع الصديقة للسياح. من المتوقع أن تعزز مبادرات التطوير السياحي الحكومية هذا القطاع أكثر.",
    publishDate: "2024-01-12",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 5,
    title: "إطلاق برامج المشترين لأول مرة",
    excerpt: "مبادرات حكومية جديدة تهدف لمساعدة المشترين لأول مرة على دخول سوق العقارات.",
    content:
      "أطلقت الحكومة عدة برامج جديدة مصممة لمساعدة المشترين لأول مرة على دخول سوق العقارات. تشمل هذه البرامج قروضاً مدعومة ومتطلبات دفعة أولى مخفضة وحوافز ضريبية للمشترين المؤهلين. المبادرات جزء من جهد أوسع لزيادة معدلات ملكية المنازل وجعل السكن أكثر إتاحة للعائلات الشابة والمهنيين. وكلاء العقارات يبلغون عن زيادة الاهتمام من المشترين لأول مرة منذ الإعلان عن البرامج.",
    publishDate: "2024-01-10",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 6,
    title: "قطاع العقارات التجارية يظهر نمواً قوياً",
    excerpt: "قطاع العقارات التجارية يشهد نمواً غير مسبوق مع تطورات الأعمال الجديدة.",
    content:
      "يشهد قطاع العقارات التجارية في أبها نمواً قوياً، مدفوعاً بتطورات الأعمال الجديدة وزيادة النشاط الاقتصادي. المساحات المكتبية والمواقع التجارية والعقارات الصناعية تشهد جميعها طلباً متزايداً. إنشاء مناطق أعمال جديدة وتوسيع المناطق التجارية الحالية يخلق فرصاً عديدة للمستثمرين. أسعار الإيجار للعقارات التجارية ارتفعت بمعدل 12% خلال العام الماضي.",
    publishDate: "2024-01-08",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 7,
    title: "تكامل تقنيات المنزل الذكي في ارتفاع",
    excerpt: "العقارات الحديثة تتميز بشكل متزايد بتقنيات المنزل الذكي وأنظمة الأتمتة.",
    content:
      "تكامل تقنيات المنزل الذكي يصبح نقطة بيع رئيسية للعقارات الحديثة في أبها. ميزات مثل الإضاءة الآلية وأنظمة الأمان والتحكم في المناخ والأجهزة الذكية تصبح بشكل متزايد قياسية في التطورات الجديدة. المشترون يظهرون تفضيلاً قوياً للعقارات مع هذه التقنيات، معتبرينها استثمارات في الراحة والأمان وكفاءة الطاقة. المطورون يستجيبون بجعل ميزات المنزل الذكي قياسية في مشاريعهم الجديدة.",
    publishDate: "2024-01-05",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 8,
    title: "فرص الاستثمار العقاري في المناطق الناشئة",
    excerpt: "مناطق جديدة تظهر كفرص استثمارية جذابة مع إمكانات نمو كبيرة.",
    content:
      "عدة مناطق ناشئة حول أبها تقدم فرصاً استثمارية جذابة لمستثمري العقارات. هذه المناطق، التي كانت تُعتبر سابقاً طرفية، تشهد الآن تطويراً متزايداً واستثماراً في البنية التحتية. المستثمرون الأوائل في هذه المناطق يحققون بالفعل عوائد كبيرة، مع ارتفاع قيم العقارات بسرعة. خبراء العقارات يوصون بهذه المناطق للمستثمرين الذين يبحثون عن عقارات عالية النمو بأسعار معقولة نسبياً.",
    publishDate: "2024-01-03",
    image: "/placeholder.svg?height=300&width=400",
  },
]
